### ISSUE TITLE
Require is incorrect

### ISSUE THREAD

**Issue by Zulgrib** [Ybalrid/systemd-numlockontty#2]
Hello,
The pkgbuild does not check for the existence of /usr/local/bin/numlock and/or does not install required package.
Alternatively, the script could try to use setleds if numlock is not found to not error.

Service currently fails with "Failed at step EXEC spawning /usr/local/bin/numlock: No such file or directory"

Maybe only AUR is not up to date.

**Comment by Ybalrid** [comment]
Hi @Zulgrib 

Please note that the actual PKGBUILD is the one hosted here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=systemd-numlockontty

An update was just pushed to the AUR that should clean up your issue. The /usr/local/bin/.... path was wrong all along

**Comment by Zulgrib** [comment]
Thank you, was not able to reproduce after your last push.
